// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCulbNRuFAqKqyMN3QPIK8dZEasMRSljDc',
    appId: '1:392230896034:web:c5138526114d43fd11b2fb',
    messagingSenderId: '392230896034',
    projectId: 'flutterfirebasedemo-b432d',
    authDomain: 'flutterfirebasedemo-b432d.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-b432d.firebasestorage.app',
    measurementId: 'G-Z623WFSQXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5cCsxRuU992zpqyCdugA8ylPqzTekPE',
    appId: '1:392230896034:android:dce39db234bafd9d11b2fb',
    messagingSenderId: '392230896034',
    projectId: 'flutterfirebasedemo-b432d',
    storageBucket: 'flutterfirebasedemo-b432d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZEyAdHlXF_dpmojEMqqu2vCmDBxJw7o',
    appId: '1:392230896034:ios:0bc19f41f91df3f311b2fb',
    messagingSenderId: '392230896034',
    projectId: 'flutterfirebasedemo-b432d',
    storageBucket: 'flutterfirebasedemo-b432d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVZEyAdHlXF_dpmojEMqqu2vCmDBxJw7o',
    appId: '1:392230896034:ios:0bc19f41f91df3f311b2fb',
    messagingSenderId: '392230896034',
    projectId: 'flutterfirebasedemo-b432d',
    storageBucket: 'flutterfirebasedemo-b432d.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCulbNRuFAqKqyMN3QPIK8dZEasMRSljDc',
    appId: '1:392230896034:web:22bbf9220d394a0211b2fb',
    messagingSenderId: '392230896034',
    projectId: 'flutterfirebasedemo-b432d',
    authDomain: 'flutterfirebasedemo-b432d.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo-b432d.firebasestorage.app',
    measurementId: 'G-4FHBZXCSSZ',
  );
}
